# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Shelving.destroy_all
Book.destroy_all
Bookshelf.destroy_all
Review.destroy_all

User.create!(
    username: 'demo',
    email: 'demo@gmail.com',
    password: 'starwars'
)

gatsby = Book.create!(title: 'The Great Gatsby', description: "eggs", author: 'F. Scott. Fitzgerald', pages: 180, published_date: 1925, image: "https://images.gr-assets.com/books/1490528560l/4671.jpg")
rises = Book.create!(title: 'The Sun Also Rises', description: 'The quintessential novel of the Lost Generation, The Sun Also Rises is one of Ernest Hemingways masterpieces, and a classic example of his spare but powerful writing style. A poignant look at the disillusionment and angst of the post-World War I generation, the novel introduces two of Hemingways most unforgettable characters: Jake Barnes and Lady Brett Ashley.', author: 'Ernest Hemingway', pages: 189, published_date: 1926, image: "https://images.gr-assets.com/books/1509899941l/36540595.jpg")
eggs = Book.create!(title: 'The Eggs of Dorchester', description: 'the quintessential novel of the Egg Generation', author: 'Humpty Bogart', pages: 1237, published_date: 1800)
pachinko = Book.create!(title: 'Pachinko', author: 'Min Jin Lee', description: 'In the early 1900s, teenaged Sunja, the adored daughter of a crippled fisherman, falls for a wealthy stranger at the seashore near her home in Korea. He promises her the world, but when she discovers she is pregnant--and that her lover is married--she refuses to be bought. Instead, she accepts an offer of marriage from a gentle, sickly minister passing through on his way to Japan. But her decision to abandon her home, and to reject her sons powerful father, sets off a dramatic saga that will echo down through the generations.', published_date: 2017, pages: 496, image: "https://images.gr-assets.com/books/1529845599l/34051011.jpg")
kitchen = Book.create!(title: 'Kitchen', author: 'Banana Yoshimoto', description: 'Banana Yoshimotos novels have made her a sensation in Japan and all over the world, and Kitchen, the dazzling English-language debut that is still her best-loved book, is an enchantingly original and deeply affecting book about mothers, love, tragedy, and the power of the kitchen and home in the lives of a pair of free-spirited young women in contemporary Japan.', pages: 152, published_date: 1988, image: "https://images.gr-assets.com/books/1327904393l/50144.jpg")
canterbury = Book.create!(title: 'Canterbury Eggs', author: 'the Duchess of Canterbury', description: 'a savage critique of App Academy', pages: 1700, published_date: 1600 )
Artist = Book.create!(title: 'An Artist of the Floating World', author: 'Kazuo Ishiguro', description: 'In the face of the misery in his homeland, the artist Masuji Ono was unwilling to devote his art solely to the celebration of physical beauty. Instead, he put his work in the service of the imperialist movement that led Japan into World War II.', pages: 206, published_date: 1986, image: "https://images.gr-assets.com/books/1327786035l/28922.jpg")
confidential = Book.create!(title: 'Kitchen Confidential: Adventures in the Culinary Underbelly', author: 'Anthony Bourdain', description: 'A deliciously funny, delectably shocking banquet of wild-but-true tales of life in the culinary trade from Chef Anthony Bourdain, laying out his more than a quarter-century of drugs, sex, and haute cuisine—now with all-new, never-before-published material.', pages: 312, published_date: 2000, image: "https://images.gr-assets.com/books/1433739086l/33313.jpg")
thief = Book.create!(title: 'The Thief From Cairo', author: 'Arsene', description: 'I had many cat-burglars in my day, but none quite like the Thief From Cairo. The Thief From Cairo was unlike other thieves, who were coarse and ungentlemanly. The Thief From Cairo was suave, seductive, elegant; he was from Cairo. He was, quite simply put, the Thief From Cairo. No one compared to the Thief From Cairo, for he was raised in a milieu completely unlike our own; he was from Cairo, and a Thief.', pages: 1, published_date: 2017)
ducks1 = Book.create!(title: 'Bath Ducks Part 1', author: 'Arsene', description: 'Two plump neckless Ducks were bobbing in a bathhouse. They were yellow little dumpling ducks, and they both wore a draped leaf upon their head, as little caps, which are very fashionable to ducks. They had large white eyes, which were always fully open and curious, but they had a vacant expression that made them look slightly dumb. All ducks like this are happily fat and always polite.', pages: 1, published_date: 1800)
ducks2 = Book.create!(title: 'Bath Ducks Part 2', author: 'Arsene', description: 'They were bobbing in the water, for their bellies were very buoyant. Of course, these baths are not like those silly ones found in American homes; they are not made of white porcelain, and they are certainly not rectangular. Instead, the baths are like great stone bowls, and the water that fills them is full of nice warm nutrients and pleasurable aromas.', pages: 1, published_date: 1800)
ducks3 = Book.create!(title: 'Bath Ducks Part 3', author: 'Arsene', description: 'A dumpling duck waddled in wearing a white towel tied tight around his midsection, and his leaf cap very wet. Being neckless, the other ducks had to paddle their whole bodies around to regard him. When they did, they doffed their leaf caps politely, then paddled astride to offer the other duck space in the bath. The approaching Duck’s towel slipped off as he neared the tub, exposing his bare ruffled tummy, but he didn’t seem to notice so it was perfectly fine.', pages: 1, published_date: 1800)
ducks4 = Book.create!(title: 'Bath Ducks Part 4', author: 'Arsene', description: 'Very soon, the bath house’s funnel came down again from a panel in the wall, and a great stream of hot water flowed into the bath from above. It hit one of the ducks on the head, causing it to submerge for a brief moment, but then it bouyanted up in the water, bobbing this way and that, the duck not even trying to regain its balance. It bobbed peacefully without the least bit of effort, for this sort of duck is always in perfect equanimity.', pages: 1, published_date: 1800)
ducks5 = Book.create!(title: 'Bath Ducks Part 5', author: 'Arsene', description: 'They all bobbed quietly for a moment, and none of them thought much of anything except for how comfortable it was in the nice warm duck water. One of them farted and it was ok. A duck quacked out two little wobbling bubbles, which hovered onto the leaf cap of the other duck, then popped on the stem like this: “pop!”', pages: 1, published_date: 1800)
ducks6 = Book.create!(title: 'Bath Ducks Part 6', author: 'Arsene', description: 'When they left, the bath was cleaned and the Ducks went to bed. They slept for a whole night, and chirped during their dreams. In the morning, one of the Ducks realized he had forgotten his leaf cap. He was concerned for a moment - all of a sudden it became very hot, the veins in his head began to throb, and his face crumpled in a fit of anxiety - but then he remembered; it would be at the bathhouse. It would be in their favorite room. All he had to do to find it was take a bath.', pages: 1, published_date: 1800)
